### ISSUE TITLE
Kleine Fehler

### ISSUE THREAD

**Issue by wernerfred** [poehlerj/gdm_sose_18#4]
Merci erst mal für die Arbeit das ganze zu digitalisieren! 👍 

Keine Kritik, sondern nur zur Info: Hab beim Lernen ein paar kleine (Leichtsinns)Fehler gefunden:
- Blatt 3, Aufgabe 3: beim Auflösen des Doppelbruchs ist ein (n+1)! zu viel im Nenner
- Blatt 3, Aufgabe 4: das 3/n im letzten Schritt müsste 2/n lauten
- Blatt 3, Aufgabe 5: im zweiten Schritt der Umformung fehlt ein Minus
- Blatt 4, Aufgabe 1: es fehlt der \ beim Definitionsbereich
- Blatt 4, Aufgabe 4: mit dem Nenner muss multipliziert werden nicht geteilt (a & b)
- Blatt 4, Aufgabe 7: da hat sich im Nenner ein x eingeschlichen, anstatt einer 2
- Blatt 5, Aufgabe 4: (x+8) im Nenner müsste (x+3) lauten

Korrigiert mich bitte wenn ich falsch liege, bin auch kein Mathe Genie 🥇 
Wenn ich mal Zeit habe kann ich das auch gerne alles abändern aber vor der Klausur wird das nichts mehr.

**Comment by poehlerj** [comment]
Danke für die Hinweise! Hab sie alle geprüft und schnell umgesetzt :+1:

**Comment by wernerfred** [comment]
Noch ein paar:
- Blatt 6, Aufgabe 38: c) der Nenner geht gegen -2 nicht gegen 2
- Blatt 6, Aufgabe 38: e) der Bruch beim Erweitern müsste im Z. und N. ein + vor der Wurzel haben und kein - und im Schritt danach fehlt das ² bei 4x
- Blatt 6, Aufgabe 38: f) mMn geht der Nenner gegen 1 nicht gegen 0, der cos dann als Ganzes gegen 0 und somit lim = 1

**Comment by Claudio-S** [comment]
Habe auch noch zwei kleinere Dinge gefunden: 
* Blatt 7, Aufgabe 43 a) fehlt die Lösung (no offense)
* Blatt 7, Aufgabe 43 e) ist m.Mn. falsch, da (x^(3+x))^x != x^(5x)
